/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package mathtool;

import java.awt.Color;
import javax.swing.JLabel;

/**
 *
 * @author Sergio
 */
public class DevelopersGUI extends javax.swing.JFrame {

    /**
     * Creates new form DevelopersGUI
     */
    public DevelopersGUI() {
        
        super("Über MathTool");
        initComponents();
        setResizable(false);
        JLabel nameLabel = new JLabel("Programm MathTool");
        JLabel developerLabel = new JLabel("Entwickler: Sergei Kovalenko");
        JLabel thanksLabel = new JLabel("Besonderer Dank gilt Dimitri Krilov und Sven Willner.");
        JLabel copyrightLabel = new JLabel("Copyright 2014 by Sergei Kovalenko.");

        nameLabel.setVisible(true);
        developerLabel.setVisible(true);
        thanksLabel.setVisible(true);
        copyrightLabel.setVisible(true);

        nameLabel.setBounds(10,10,300,25);
        developerLabel.setBounds(10,40,300,25);
        thanksLabel.setBounds(10,70,300,25);
        copyrightLabel.setBounds(10,150,300,25);

        add(nameLabel);
        add(developerLabel);
        add(thanksLabel);
        add(copyrightLabel);

        this.setBounds(400,200,400,210);
        this.getContentPane().setBackground(Color.white);
        validate();
        repaint();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(DevelopersGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(DevelopersGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(DevelopersGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(DevelopersGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//
//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new DevelopersGUI().setVisible(true);
//            }
//        });
//    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
