package mathtool;

public enum TypeCommand {

    APPROX, CDNF, CLEAR, DEF, DEFFUNCS, DEFVARS, EULER, EXPAND, LATEX, PI, PLOT2D, 
    PLOT3D, PLOTCURVE, PLOTPOLAR, SOLVE, SOLVEDEQ, TABLE, TANGENT, TAYLORDEQ, 
    UNDEF, UNDEFALL;

}
