package algorithmexecuter.exceptions.constants;

public abstract class CompileExceptionTexts {
    
    public static final String AC_IDENTIFIER_ALREADY_DEFINED = "AC_IDENTIFIER_ALREADY_DEFINED";
    public static final String AC_INCOMPATIBLE_TYPES = "AC_INCOMPATIBLE_TYPES";    
    public static final String AC_FILE_MUST_CONTAIN_A_BEGIN = "AC_FILE_MUST_CONTAIN_A_BEGIN";    
    public static final String AC_FILE_MUST_CONTAIN_AN_END = "AC_FILE_MUST_CONTAIN_AN_END";    
    public static final String AC_END_BEFORE_BEGIN = "AC_END_BEFORE_BEGIN";    
    public static final String AC_ALGORITHM_ALREADY_EXISTS = "AC_ALGORITHM_ALREADY_EXISTS";    
    public static final String AC_ALGORITHM_MUST_START_WITH_BEGIN = "AC_ALGORITHM_MUST_START_WITH_BEGIN";    
    public static final String AC_ALGORITHM_MUST_END_WITH_END = "AC_ALGORITHM_MUST_END_WITH_END";    
    public static final String AC_ALGORITHM_HAS_NO_NAME = "AC_ALGORITHM_HAS_NO_NAME";    
    public static final String AC_IDENTIFIER_EXPECTED = "AC_IDENTIFIER_EXPECTED";    
    public static final String AC_BRACKET_EXPECTED = "AC_BRACKET_EXPECTED";    
    public static final String AC_EXPECTED = "AC_EXPECTED";
    public static final String AC_CANNOT_FIND_SYMBOL = "AC_CANNOT_FIND_SYMBOL";    
    public static final String AC_ILLEGAL_CHARACTER = "AC_ILLEGAL_CHARACTER";    
    public static final String AC_COMMAND_COUND_NOT_BE_PARSED = "AC_COMMAND_COUND_NOT_BE_PARSED";    
    public static final String AC_CONTROL_STRUCTURE_MUST_CONTAIN_BEGIN_AND_END = "AC_CONTROL_STRUCTURE_MUST_CONTAIN_BEGIN_AND_END";    
    public static final String AC_CONTROL_STRUCTURE_FOR_NEW_IDENTIFIER_NOT_ALLOWED = "AC_CONTROL_STRUCTURE_FOR_NEW_IDENTIFIER_NOT_ALLOWED";    
    public static final String AC_KEYWORD_EXPECTED = "AC_KEYWORD_EXPECTED";    
    public static final String AC_KEYWORD_NOT_ALLOWED_HERE = "AC_KEYWORD_NOT_ALLOWED_HERE";    
    public static final String AC_MISSING_LINE_SEPARATOR = "AC_MISSING_LINE_SEPARATOR";    
    public static final String AC_WRONG_NUMBER_OF_INPUT_PARAMETERS = "AC_WRONG_NUMBER_OF_INPUT_PARAMETERS";
    public static final String AC_WRONG_TYPE_OF_INPUT_PARAMETERS = "AC_WRONG_TYPE_OF_INPUT_PARAMETERS";
    public static final String AC_MAIN_ALGORITHM_DOES_NOT_EXIST = "AC_MAIN_ALGORITHM_DOES_NOT_EXIST";
    public static final String AC_MAIN_ALGORITHM_NOT_ALLOWED_TO_CONTAIN_PARAMETERS = "AC_MAIN_ALGORITHM_NOT_ALLOWED_TO_CONTAIN_PARAMETERS";
    public static final String AC_VOID_ALGORITHM_MUST_CONTAIN_ONLY_SIMPLE_RETURNS = "AC_VOID_ALGORITHM_MUST_CONTAIN_ONLY_SIMPLE_RETURNS";
    public static final String AC_MISSING_RETURN_STATEMENT = "AC_MISSING_RETURN_STATEMENT";
    public static final String AC_WRONG_RETURN_TYPE = "AC_WRONG_RETURN_TYPE";
    public static final String AC_UNREACHABLE_CODE = "AC_UNREACHABLE_CODE";
    public static final String AC_IDENTIFIER_MAYBE_NOT_INITIALIZED = "AC_IDENTIFIER_MAYBE_NOT_INITIALIZED";
    public static final String AC_BOOLEAN_EXPRESSION_EMPTY_OR_INCOMPLETE = "AC_BOOLEAN_EXPRESSION_EMPTY_OR_INCOMPLETE";
    public static final String AC_LEFT_SIDE_OF_BOOLEAN_BINARY_EXPRESSION_IS_EMPTY = "AC_LEFT_SIDE_OF_BOOLEAN_BINARY_EXPRESSION_IS_EMPTY";
    public static final String AC_RIGHT_SIDE_OF_BOOLEAN_BINARY_EXPRESSION_IS_EMPTY = "AC_RIGHT_SIDE_OF_BOOLEAN_BINARY_EXPRESSION_IS_EMPTY";
    public static final String AC_BOOLEAN_EXPRESSION_CANNOT_BE_INTERPRETED = "AC_BOOLEAN_EXPRESSION_CANNOT_BE_INTERPRETED";
    
    public static final String AC_UNKNOWN_ERROR = "AC_UNKNOWN_ERROR";    
    
}
